### ISSUE TITLE
Blocking Jersey

### ISSUE THREAD

**Issue by robertjchristian** [Netflix/karyon#108]
Hello, 

I am looking for clarification on what "blocking" jersey means.  

Mainly, is the downstream processing handled by the same thread used to handle the inbound request, or is the request thread returned to the container prior to the Jersey invocation?  

I output this stacktrace from within the Jersey Hello World example:

<pre>
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1364)
	at com.netflix.karyon.examples.hellonoss.server.jersey.HelloworldResource.helloTo(HelloworldResource.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
	at com.netflix.karyon.jersey.blocking.JerseyBasedRouter.route(JerseyBasedRouter.java:47)
	at com.netflix.karyon.jersey.blocking.JerseyBasedRouter.route(JerseyBasedRouter.java:24)
	at com.netflix.karyon.transport.interceptor.InterceptorExecutor$ChainSubscriber.onCompleted(InterceptorExecutor.java:190)
	at rx.internal.operators.OperatorMap$1.onCompleted(OperatorMap.java:43)
	at rx.Observable$3.call(Observable.java:1552)
	at rx.Observable$3.call(Observable.java:1546)
	at rx.Observable$2.call(Observable.java:159)
	at rx.Observable$2.call(Observable.java:155)
	at rx.Observable.unsafeSubscribe(Observable.java:6831)
	at com.netflix.karyon.transport.interceptor.InterceptorExecutor$ChainSubscriber.handleResult(InterceptorExecutor.java:202)
	at com.netflix.karyon.transport.interceptor.InterceptorExecutor$ChainSubscriber.onCompleted(InterceptorEx                                                                  ecutor.java:188)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:48)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:29)
	at rx.Observable$2.call(Observable.java:159)
	at rx.Observable$2.call(Observable.java:155)
	at rx.Observable.subscribe(Observable.java:6900)
	at io.reactivex.netty.protocol.http.server.HttpConnectionHandler$1$1.onNext(HttpConnectionHandler.java:113)
	at io.reactivex.netty.protocol.http.server.HttpConnectionHandler$1$1.onNext(HttpConnectionHandler.java:62)
	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:224)
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:101)
	at io.reactivex.netty.pipeline.ObservableAdapter.channelRead(ObservableAdapter.java:40)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.reactivex.netty.protocol.http.server.ServerRequestResponseConverter.channelRead(ServerRequestResponseConverter.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.access$700(AbstractChannelHandlerContext.java:32)
	at io.netty.channel.AbstractChannelHandlerContext$8.run(AbstractChannelHandlerContext.java:324)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java                                                                                 :116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:744)

</pre>

Thanks,

Rob

**Comment by victuxbb** [comment]
Hi, I'm interested in this question too :+1:

**Comment by NiteshKant** [comment]
Since karyon 2 uses RxNetty which is an asynchronous (non-blocking) networking library, the jersey module makes it explicit that the module is synchronous (blocking). 

The threading model is as follows:

```
Netty Event Loop -> RxJava IO Scheduler -> Jersey Module
```

For non-blocking request handling (asynchronous modules), the threading model will look like:

```
Netty Event Loop -> Any asynchronous Module
```

The relevant code that switches the thread (use RxJava IO scheduler) is [here](https://github.com/Netflix/karyon/blob/master/karyon2-jersey-blocking/src/main/java/netflix/karyon/jersey/blocking/JerseyBasedRouter.java#L94)
