### ISSUE TITLE
KaryonGuiceContextListener chokes when war filename contains "#"

### ISSUE THREAD

**Issue by nfriedly** [Netflix/karyon#182]
I need my `watson-dashboard.war` file's root context to be two "folders" instead of the usual one: `/watson-dashboard/ui` instead of just `/watson-dashboard`. I renamed it to `watson-dashboard#ui.war` per http://tomcat.apache.org/tomcat-7.0-doc/config/context.html#Naming and that does make tomcat load it at the correct URL, but the servlet fails to start now :(

This is from my catalina.out:

	015-01-23 16:00:40,473 [http-bio-8080-exec-8] INFO  com.netflix.config.sources.URLConfigurationSource  - URLs to be used as dynamic configuration source: [file:/usr/local/apache-tomcat-7.0.57/webapps/watson-dashboard%23ui/WEB-INF/classes/config.properties]
	2015-01-23 16:00:40,486 [http-bio-8080-exec-8] INFO  com.netflix.karyon.server.ArchaiusIntegrationInterceptor  - Loading application properties with app id: WATSON_DASHBOARD and environment: null
	2015-01-23 16:00:40,508 [http-bio-8080-exec-8] INFO  com.netflix.config.util.ConfigurationUtils  - Loaded properties file file:/usr/local/apache-tomcat-7.0.57/webapps/watson-dashboard%23ui/WEB-INF/classes/WATSON_DASHBOARD.properties
	2015-01-23 16:00:40,518 [http-bio-8080-exec-8] INFO  com.netflix.karyon.server.ServerBootstrap  - Creating a new governator classpath scanner with base packages: [com.netflix, com.ibm.csf]
	Jan 23, 2015 4:00:40 PM org.apache.catalina.core.StandardContext listenerStart
	SEVERE: Error configuring application listener of class com.netflix.karyon.server.guice.KaryonGuiceContextListener
	java.lang.IllegalStateException: java.io.FileNotFoundException: /usr/local/apache-tomcat-7.0.57/webapps/watson-dashboard%23ui/WEB-INF/lib/archaius-core-0.6.0.jar (No such file or directory)
			at org.apache.xbean.finder.archive.JarArchive.<init>(JarArchive.java:55)
			at com.netflix.governator.lifecycle.ClasspathScanner.doScanning(ClasspathScanner.java:134)
			at com.netflix.governator.lifecycle.ClasspathScanner.<init>(ClasspathScanner.java:87)
			at com.netflix.governator.lifecycle.ClasspathScanner.<init>(ClasspathScanner.java:61)
			at com.netflix.governator.guice.LifecycleInjector.createStandardClasspathScanner(LifecycleInjector.java:126)
			at com.netflix.karyon.server.ServerBootstrap.initialize(ServerBootstrap.java:114)
			at com.netflix.karyon.server.KaryonServer.<init>(KaryonServer.java:166)
			at com.netflix.karyon.server.KaryonServer.<init>(KaryonServer.java:138)
			at com.netflix.karyon.server.guice.KaryonGuiceContextListener.<init>(KaryonGuiceContextListener.java:62)
			at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
			at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
			at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
			at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
			at java.lang.Class.newInstance(Class.java:438)
			at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:116)
			at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4909)
			at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5492)
			at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
			at org.apache.catalina.manager.ManagerServlet.start(ManagerServlet.java:1286)
			at org.apache.catalina.manager.HTMLManagerServlet.start(HTMLManagerServlet.java:694)
			at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:217)
			at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
			at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
			at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:213)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
			at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
			at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
			at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
			at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
			at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:612)
			at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
			at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
			at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
			at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
			at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
			at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
			at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
			at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
			at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
			at java.lang.Thread.run(Thread.java:745)
	Caused by: java.io.FileNotFoundException: /usr/local/apache-tomcat-7.0.57/webapps/watson-dashboard%23ui/WEB-INF/lib/archaius-core-0.6.0.jar (No such file or directory)
			at java.util.zip.ZipFile.open(Native Method)
			at java.util.zip.ZipFile.<init>(ZipFile.java:220)
			at java.util.zip.ZipFile.<init>(ZipFile.java:150)
			at java.util.jar.JarFile.<init>(JarFile.java:166)
			at java.util.jar.JarFile.<init>(JarFile.java:103)
			at org.apache.xbean.finder.archive.JarArchive.<init>(JarArchive.java:53)
			... 48 more

	Jan 23, 2015 4:00:40 PM org.apache.catalina.core.StandardContext listenerStart
	SEVERE: Skipped installing application listeners due to previous error(s)

Is there a simple way around this?

**Comment by jschoudt** [comment]
If you use xbean-finder 3.13 instead of 3.11.1 this issue is resolved.  However, later 3.x releases of xbean use a later version of the asm libs which can cause a conflict with the version required by guice.

Not sure if 3.13 introduces other issues, I haven't hit any yet.
