### ISSUE TITLE
Error processing freemarker template @ /webadmin/niws/index.ftl

### ISSUE THREAD

**Issue by brharrington** [Netflix/karyon#183]
I'm getting an exception in the logs when I run with a customized path for the admin:

```
2015-01-24T23:28:22.435 ERROR [qtp1064456966-67] netflix.admin.AdminFreemarkerTemplateProvider: Error processing freemarker template @ /webadmin/niws/index.ftl: Error reading included file webadmin/niws/index.ftl
freemarker.template.TemplateException: Error reading included file webadmin/niws/index.ftl
    at freemarker.core.Include.accept(Include.java:167) ~[freemarker-2.3.15.jar:2.3.15]
    at freemarker.core.Environment.visit(Environment.java:209) ~[freemarker-2.3.15.jar:2.3.15]
    at freemarker.core.MixedContent.accept(MixedContent.java:92) ~[freemarker-2.3.15.jar:2.3.15]
    at freemarker.core.Environment.visit(Environment.java:209) ~[freemarker-2.3.15.jar:2.3.15]
    at freemarker.core.Environment.process(Environment.java:189) ~[freemarker-2.3.15.jar:2.3.15]
    at freemarker.template.Template.process(Template.java:237) ~[freemarker-2.3.15.jar:2.3.15]
    at netflix.admin.AdminFreemarkerTemplateProvider.writeTo(AdminFreemarkerTemplateProvider.java:172) [karyon-admin-2.2.00-ALPHA7.jar:?]
    at netflix.admin.AdminFreemarkerTemplateProvider.writeTo(AdminFreemarkerTemplateProvider.java:51) [karyon-admin-2.2.00-ALPHA7.jar:?]
    at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302) [jersey-server-1.18.1.jar:1.18.1]
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510) [jersey-server-1.18.1.jar:1.18.1]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [jersey-server-1.18.1.jar:1.18.1]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [jersey-server-1.18.1.jar:1.18.1]
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [jersey-servlet-1.18.1.jar:1.18.1]
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540) [jersey-servlet-1.18.1.jar:1.18.1]
    at netflix.adminresources.AdminResourcesFilter.service(AdminResourcesFilter.java:67) [karyon-admin-2.2.00-ALPHA7.jar:?]
    at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:909) [jersey-servlet-1.18.1.jar:1.18.1]
    at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:857) [jersey-servlet-1.18.1.jar:1.18.1]
    at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:811) [jersey-servlet-1.18.1.jar:1.18.1]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1300) [jetty-servlet-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:445) [jetty-servlet-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1038) [jetty-server-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:374) [jetty-servlet-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:972) [jetty-server-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) [jetty-server-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.server.Server.handle(Server.java:363) [jetty-server-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483) [jetty-server-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:920) [jetty-server-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:982) [jetty-server-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635) [jetty-http-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235) [jetty-http-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627) [jetty-io-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51) [jetty-io-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-7.6.7.v20120910.jar:7.6.7.v20120910]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-7.6.7.v20120910.jar:7.6.7.v20120910]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.io.FileNotFoundException: Template webadmin/niws/index.ftl not found.
    at freemarker.template.Configuration.getTemplate(Configuration.java:489) ~[freemarker-2.3.15.jar:2.3.15]
    at freemarker.core.Environment.getTemplateForInclusion(Environment.java:1464) ~[freemarker-2.3.15.jar:2.3.15]
    at freemarker.core.Include.accept(Include.java:157) ~[freemarker-2.3.15.jar:2.3.15]
    ... 37 more
```

The paths I'm setting are:

```
netflix.admin.template.context=/baseserver
netflix.admin.resource.context=/v1/platform/base
```

**Comment by brharrington** [comment]
It looks like internally we have something regularly polling for the set of niws clients by hitting `/v1/platform/base/niws`. Instead of returning a 404 it is returning a 500 and logs the exception above.

```
$ curl -vs 'http://localhost:8077/v1/platform/base/niws'
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8077 (#0)
> GET /v1/platform/base/niws HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8077
> Accept: */*
> 
< HTTP/1.1 500 Server Error
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/html;charset=ISO-8859-1
< Content-Length: 1294
* Server Jetty(7.6.7.v20120910) is not blacklisted
< Server: Jetty(7.6.7.v20120910)
< 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 Server Error</title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /v1/platform/base/niws. Reason:
<pre>    Server Error</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
</body>
</html>
```
