### ISSUE TITLE
3.x admin server now requires ui module to be installed

### ISSUE THREAD

**Issue by brharrington** [Netflix/karyon#310]
PR #306 breaks the ability to use AdminServerModule without using AdminUIServerModule. Specifically AdminHttpHandler will fail to be created if just using AdminServerModule:

```
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for com.netflix.karyon.admin.ui.AdminUIServerConfig was bound.
  while locating com.netflix.karyon.admin.ui.AdminUIServerConfig
    for parameter 3 at com.netflix.karyon.admin.rest.AdminHttpHandler.<init>(AdminHttpHandler.java:59)
  while locating com.netflix.karyon.admin.rest.AdminHttpHandler
    for parameter 1 at com.netflix.iep.karyon3.DefaultHandler.<init>(DefaultHandler.java:34)
  at com.netflix.iep.karyon3.CompatModule.getAdminServer(CompatModule.java:50) (via modules: com.netflix.iep.karyon3.KaryonModule -> com.google.inject.util.Modules$OverrideModule -> com.netflix.iep.karyon3.CompatModule)

1 error
```

It seems like the rest/* classes should not depend on the ui/* classes.

**Comment by elandau** [comment]
3.x branch no longer under development
